-- Optional sample data for local demos.
-- Apply after `supabase db reset` with:
--   supabase db query --file supabase/seed.sample.sql

do $$
declare
  user_akari constant uuid := '11111111-1111-1111-1111-111111111111';
begin
  insert into public.works (
    id,
    created_by,
    source_type,
    tmdb_media_type,
    tmdb_id,
    work_type,
    parent_work_id,
    title,
    original_title,
    search_text,
    overview,
    poster_path,
    release_date,
    runtime_minutes,
    typical_episode_runtime_minutes,
    duration_bucket,
    episode_count,
    season_count,
    season_number,
    genres,
    focus_required_score,
    background_fit_score,
    completion_load_score,
    created_at,
    updated_at
  )
  values
    (
      'cccccccc-cccc-cccc-cccc-ccccccccccc1',
      user_akari,
      'tmdb',
      'movie',
      1366,
      'movie',
      null,
      'ロッキー',
      'Rocky',
      'ロッキー rocky ドラマ',
      '努力して前に進みたい日に置いておく定番。',
      '/y4dh1zqKfydmPY7VmjZ0c7IbXO4.jpg',
      '1976-12-03',
      119,
      null,
      'long',
      null,
      null,
      null,
      array['Drama'],
      50,
      25,
      50,
      now() - interval '14 days',
      now() - interval '14 days'
    ),
    (
      'cccccccc-cccc-cccc-cccc-ccccccccccc2',
      user_akari,
      'tmdb',
      'tv',
      2304,
      'series',
      null,
      'きかんしゃトーマス',
      'Thomas & Friends',
      'きかんしゃトーマス thomas & friends アニメーション kids',
      '気軽に流せるシリーズの見本データ。',
      '/wrFb5dE2yxUjz3a5V7PEXPPzsFU.jpg',
      '1984-10-09',
      null,
      22,
      'short',
      24,
      24,
      null,
      array['Animation', 'Kids'],
      25,
      75,
      100,
      now() - interval '13 days',
      now() - interval '13 days'
    ),
    (
      'cccccccc-cccc-cccc-cccc-ccccccccccc3',
      user_akari,
      'tmdb',
      'movie',
      24428,
      'movie',
      null,
      'アベンジャーズ',
      'The Avengers',
      'アベンジャーズ avengers',
      '人が多い盤面や並び替え確認に使う追加カード。',
      '/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
      '2012-04-25',
      143,
      null,
      'very_long',
      null,
      null,
      null,
      array['Action', 'Science Fiction'],
      75,
      25,
      75,
      now() - interval '12 days',
      now() - interval '12 days'
    )
  on conflict (id) do update
  set
    created_by = excluded.created_by,
    source_type = excluded.source_type,
    tmdb_media_type = excluded.tmdb_media_type,
    tmdb_id = excluded.tmdb_id,
    work_type = excluded.work_type,
    parent_work_id = excluded.parent_work_id,
    title = excluded.title,
    original_title = excluded.original_title,
    search_text = excluded.search_text,
    overview = excluded.overview,
    poster_path = excluded.poster_path,
    release_date = excluded.release_date,
    runtime_minutes = excluded.runtime_minutes,
    typical_episode_runtime_minutes = excluded.typical_episode_runtime_minutes,
    duration_bucket = excluded.duration_bucket,
    episode_count = excluded.episode_count,
    season_count = excluded.season_count,
    season_number = excluded.season_number,
    genres = excluded.genres,
    focus_required_score = excluded.focus_required_score,
    background_fit_score = excluded.background_fit_score,
    completion_load_score = excluded.completion_load_score,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at;

  insert into public.backlog_items (
    id,
    user_id,
    work_id,
    status,
    primary_platform,
    note,
    sort_order,
    created_at,
    updated_at,
    last_interacted_at
  )
  values
    (
      'dddddddd-dddd-dddd-dddd-ddddddddddd1',
      user_akari,
      'cccccccc-cccc-cccc-cccc-ccccccccccc1',
      'stacked',
      'u_next',
      '追加サンプル 1。',
      2000,
      now() - interval '14 days',
      now() - interval '14 days',
      now() - interval '14 days'
    ),
    (
      'dddddddd-dddd-dddd-dddd-ddddddddddd2',
      user_akari,
      'cccccccc-cccc-cccc-cccc-ccccccccccc2',
      'stacked',
      null,
      '追加サンプル 2。',
      3000,
      now() - interval '13 days',
      now() - interval '13 days',
      now() - interval '13 days'
    ),
    (
      'dddddddd-dddd-dddd-dddd-ddddddddddd3',
      user_akari,
      'cccccccc-cccc-cccc-cccc-ccccccccccc3',
      'stacked',
      'disney_plus',
      '追加サンプル 3。',
      4000,
      now() - interval '12 days',
      now() - interval '12 days',
      now() - interval '12 days'
    )
  on conflict (id) do update
  set
    user_id = excluded.user_id,
    work_id = excluded.work_id,
    status = excluded.status,
    primary_platform = excluded.primary_platform,
    note = excluded.note,
    sort_order = excluded.sort_order,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    last_interacted_at = excluded.last_interacted_at;
end
$$;
